const config = {
  apiKey: process.env.REACT_APP_FIREBASE_GOOGLEAUTH_APIKEY,
  authDomain: process.env.REACT_APP_FIREBASE_GOOGLEAUTH_AUTHDOMAIN,
  projectId: process.env.REACT_APP_FIREBASE_GOOGLEAUTH_PROJECTID,
  storageBucket: process.env.REACT_APP_FIREBASE_GOOGLEAUTH_STORAGEBUCKET,
  messagingSenderId: process.env.REACT_APP_FIREBASE_GOOGLEAUTH_MESSAGINGSENDERID,
  appId: process.env.REACT_APP_FIREBASE_GOOGLEAUTH_APPID,
  measurementId: process.env.REACT_APP_FIREBASE_GOOGLEAUTH_MEASUREMENTID
};

export default config;